// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn7hDiuyzGrQOSx1AXjQSFhn_x_ExsirI',
    appId: '1:839148412972:web:69f400d1948c361bccf189',
    messagingSenderId: '839148412972',
    projectId: 'flutterfire-3d3b0',
    authDomain: 'flutterfire-3d3b0.firebaseapp.com',
    storageBucket: 'flutterfire-3d3b0.appspot.com',
    measurementId: 'G-9NT2RH8LSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ5xyFPLGo5kwgxqiAqxSzeq1yAIB6ODM',
    appId: '1:839148412972:android:4e7c604b8c7ed695ccf189',
    messagingSenderId: '839148412972',
    projectId: 'flutterfire-3d3b0',
    storageBucket: 'flutterfire-3d3b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79ZnIIGi5EzKDooKgwb_Tj8dtgHR2Lck',
    appId: '1:839148412972:ios:445e99c3fbabf9b3ccf189',
    messagingSenderId: '839148412972',
    projectId: 'flutterfire-3d3b0',
    storageBucket: 'flutterfire-3d3b0.appspot.com',
    androidClientId: '839148412972-1omrkalaclsk0600v76n0i46ks6mk9id.apps.googleusercontent.com',
    iosClientId: '839148412972-cll03ht0t6hq8c6ojcvrf3b9f6kvsu1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffLoginGpt4',
  );
}
